# Generated by Django 2.2.6 on 2020-08-25 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Черновик', 'Черновик'), ('Сохранено', 'Сохранено'), ('Оплачено', 'Оплачено'), ('Помечено на удаление', 'Помечено на удаление')], default='Черновик', max_length=64, verbose_name='Статус')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('familyname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('father_name', models.CharField(max_length=64, verbose_name='Отчество')),
                ('driver_age', models.IntegerField(verbose_name='Возвраст')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('brand', models.CharField(max_length=32, verbose_name='Марка')),
                ('model', models.CharField(max_length=64, verbose_name='Модель')),
                ('number_of_drivers', models.IntegerField(verbose_name='Число водителей')),
                ('kmb', models.FloatField(verbose_name='Кмб')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car_year', models.IntegerField(verbose_name='Год выпуска')),
                ('insurance_amount', models.IntegerField(verbose_name='Страховая сумма')),
                ('class_master', models.IntegerField(verbose_name='Класс автомастерской')),
                ('accident_caused_by_third_parties', models.BooleanField(verbose_name='ДТП по вине третьих лиц')),
                ('accident_caused_by_drivers_of_the_insured_car', models.BooleanField(verbose_name='ДТП по вине водителей застрахованного ТС')),
                ('damage', models.BooleanField(verbose_name='Механические повреждения')),
                ('broken_glass', models.BooleanField(verbose_name='Бой стекол ТС')),
                ('unlawful_actions_of_third_parties', models.BooleanField(verbose_name='Противоправние действия третьих лиц')),
                ('hijacking', models.BooleanField(verbose_name='Хищение')),
                ('total_damage', models.BooleanField(verbose_name='Только тотальный ущерб')),
                ('at_a_time', models.BooleanField(default=0, verbose_name='Единовременно')),
                ('installment_plan', models.BooleanField(default=0, verbose_name='Рассрочка')),
                ('number_of_payments', models.IntegerField(verbose_name='Количество платежей')),
                ('insurance_period', models.IntegerField(default=12, null=True, verbose_name='Срок страхования')),
                ('prize_kf', models.FloatField(verbose_name='Коэффициент соотношения выплат к премиям')),
                ('anderright_kf', models.FloatField(verbose_name='Андреррайтерский коэффициент')),
                ('insurance_liability', models.IntegerField(verbose_name='Страховая сумма')),
                ('insurance_prize_osago', models.IntegerField(verbose_name='Страховая премия по ОСАГО')),
                ('insurance_accident', models.IntegerField(verbose_name='Страховая сумма')),
                ('insurance_places', models.CharField(max_length=64, verbose_name='Застрахованные посадочные места')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Страхователь',
                'verbose_name_plural': 'Страхователи',
            },
        ),
    ]
