# Generated by Django 2.2.6 on 2020-08-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policyholder',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='policyholder',
            old_name='kmb',
            new_name='kbm',
        ),
        migrations.RenameField(
            model_name='policyholder',
            old_name='familyname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='at_a_time',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='installment_plan',
        ),
    ]
